// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgriexgafrzhtvjgkgux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ncmlleGdhZnJ6aHR2amdrZ3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTU2MjAsImV4cCI6MjA1Nzc3MTYyMH0.1dw4MC8Cwlxq21mRdd2Km6hfXPOgT_hPZmnkejud3pU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);